---
# ESPHome config for esp32 camera
# run esphome flashing: $ esphome run esp32camera.yaml
# run esphome gui: $ esphome dashboard .
esphome:
  name: esp32camera1
  platform: ESP32
  board: esp32dev

wifi:
  ssid: !secret ssid
  password: !secret password

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_pass

# Add webserver on port 80.
#web_server:
#  port: 80

# Enable update Over-The-Air
ota:
  password: !secret ota_pass

esp32_camera:
  name: mycamera-1
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
# image settings:
  resolution: 1600x1200

# Flashlight
output:
  - platform: gpio
    pin: GPIO4
    id: gpio_4

## GPIO_4 is the flash light pin
light:
  - platform: binary
    output: gpio_4
    name: esp32camera1 light
